# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CreateContours_ModelBuilderTemplate.py
# Created on: 2021-09-15 13:45:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: CreateContours_ModelBuilderTemplate <Lake_Name> <TIN_Surface> <Workspace> <Contour_interval> <Base_contour> <Max_Spillway_Elevation> <Water_surface_Elevation> <Map_Resolution> <Smoothing_Tolerance> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Script arguments
Lake_Name = arcpy.GetParameterAsText(0)
if Lake_Name == '#' or not Lake_Name:
    Lake_Name = "OldBethanyTest" # provide a default value if unspecified

TIN_Surface = arcpy.GetParameterAsText(1)
if TIN_Surface == '#' or not TIN_Surface:
    TIN_Surface = "C:\\Users\\loyler\\OneDrive - DOI\\Desktop\\OldBethanyTest\\GIS\\OldBethany_prelimTIN" # provide a default value if unspecified

Workspace = arcpy.GetParameterAsText(2)
if Workspace == '#' or not Workspace:
    Workspace = "C:\\Users\\loyler\\OneDrive - DOI\\Desktop\\OldBethanyTest\\GIS\\OldBethanyTest.gdb" # provide a default value if unspecified

Contour_interval = arcpy.GetParameterAsText(3)
if Contour_interval == '#' or not Contour_interval:
    Contour_interval = "2" # provide a default value if unspecified

Base_contour = arcpy.GetParameterAsText(4)
if Base_contour == '#' or not Base_contour:
    Base_contour = "884" # provide a default value if unspecified

Max_Spillway_Elevation = arcpy.GetParameterAsText(5)
if Max_Spillway_Elevation == '#' or not Max_Spillway_Elevation:
    Max_Spillway_Elevation = "903.1" # provide a default value if unspecified

Water_surface_Elevation = arcpy.GetParameterAsText(6)
if Water_surface_Elevation == '#' or not Water_surface_Elevation:
    Water_surface_Elevation = "900.3" # provide a default value if unspecified

Map_Resolution = arcpy.GetParameterAsText(7)
if Map_Resolution == '#' or not Map_Resolution:
    Map_Resolution = "CELLSIZE 0.5" # provide a default value if unspecified

Smoothing_Tolerance = arcpy.GetParameterAsText(8)
if Smoothing_Tolerance == '#' or not Smoothing_Tolerance:
    Smoothing_Tolerance = "1.5 Meters" # provide a default value if unspecified

# Local variables:
v_Lake_Name__raster = "%Workspace%/%Lake Name%_raster"
v_Lake_Name__contoursfromraster01 = "%Workspace%/%Lake Name%_contoursfromraster01"
v_Lake_Name__spillwayelev = "%Workspace%/%Lake Name%_spillwayelev"
v_Lake_Name__wsel = "%Workspace%/%Lake Name%_wsel"
v_Lake_Name__contoursfromraster = "%Workspace%/%Lake Name%_contoursfromraster"
v_Lake_Name__selected = "%Workspace%/%Lake Name%_selected"
v_Lake_Name__allcontoursUnsmoothed = "%Workspace%/%Lake Name%_allcontoursUnsmoothed"
v_Lake_Name__smoothed = "%Workspace%/%Lake Name%_smoothed"

# Process: TIN to Raster
tempEnvironment0 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = "PROJCS['NAD_1983_2011_UTM_Zone_15N',GEOGCS['GCS_NAD_1983_2011',DATUM['D_NAD_1983_2011',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-93.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]"
arcpy.TinRaster_3d(TIN_Surface, v_Lake_Name__raster, "FLOAT", "LINEAR", Map_Resolution, "1")
arcpy.env.outputCoordinateSystem = tempEnvironment0

# Process: Contour (2)
arcpy.Contour_3d(v_Lake_Name__raster, v_Lake_Name__contoursfromraster01, "0.1", Water_surface_Elevation, "1", "CONTOUR", "")

# Process: Select (2)
arcpy.Select_analysis(v_Lake_Name__contoursfromraster01, v_Lake_Name__spillwayelev, "Contour = %Max Spillway Elevation%")

# Process: Select
arcpy.Select_analysis(v_Lake_Name__contoursfromraster01, v_Lake_Name__wsel, "Contour =%Water-surface Elevation%")

# Process: Contour
arcpy.Contour_3d(v_Lake_Name__raster, v_Lake_Name__contoursfromraster, Contour_interval, Base_contour, "1", "CONTOUR", "")

# Process: Select (3)
arcpy.Select_analysis(v_Lake_Name__contoursfromraster, v_Lake_Name__selected, "( Shape_Length >500) AND ( Contour < %Max Spillway Elevation% + %Contour interval%)")

# Process: Merge
arcpy.Merge_management("'%Workspace%/%Lake Name%_spillwayelev';'%Workspace%/%Lake Name%_wsel';'%Workspace%/%Lake Name%_selected'", v_Lake_Name__allcontoursUnsmoothed, "Shape_Length \"Shape_Length\" true true true 0 Double 0 0 ,First,#,%Workspace%/%Lake Name%_spillwayelev,Shape_Length,-1,-1,%Workspace%/%Lake Name%_spillwayelev,Shape_length,-1,-1,%Workspace%/%Lake Name%_wsel,Shape_Length,-1,-1,%Workspace%/%Lake Name%_wsel,Shape_length,-1,-1,%Workspace%/%Lake Name%_selected,Shape_Length,-1,-1,%Workspace%/%Lake Name%_selected,Shape_length,-1,-1;CONTOUR \"CONTOUR\" true true false 0 Double 0 0 ,First,#,%Workspace%/%Lake Name%_spillwayelev,CONTOUR,-1,-1,%Workspace%/%Lake Name%_wsel,CONTOUR,-1,-1,%Workspace%/%Lake Name%_selected,CONTOUR,-1,-1")

# Process: Smooth Line
arcpy.SmoothLine_cartography(v_Lake_Name__allcontoursUnsmoothed, v_Lake_Name__smoothed, "PAEK", Smoothing_Tolerance, "FIXED_CLOSED_ENDPOINT", "NO_CHECK", "")

