# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CreateCUBEUncertaintyMap_ModelBuilderArcPyTemplate.py
# Created on: 2021-10-05 11:57:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: CreateCUBEUncertaintyMap_ModelBuilderArcPyTemplate <Lake_Name> <Output_QA_Geodatabase> <QA_Folder> <MB_Extent_Polygon> <Final_xyz_map_thinned_points> <Map_Resolution__meters_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Lake_Name = arcpy.GetParameterAsText(0)
if Lake_Name == '#' or not Lake_Name:
    Lake_Name = "MilanCityLake" # provide a default value if unspecified

Output_QA_Geodatabase = arcpy.GetParameterAsText(1)
if Output_QA_Geodatabase == '#' or not Output_QA_Geodatabase:
    Output_QA_Geodatabase = "E:\\HYPACK_Projects\\2020_DNR_Lakes\\2020-07_MilanCityLake\\GIS\\QA\\MilanCityLake_QA.gdb" # provide a default value if unspecified

QA_Folder = arcpy.GetParameterAsText(2)
if QA_Folder == '#' or not QA_Folder:
    QA_Folder = "E:\\HYPACK_Projects\\2020_DNR_Lakes\\2020-07_MilanCityLake\\GIS\\QA" # provide a default value if unspecified

MB_Extent_Polygon = arcpy.GetParameterAsText(3)
if MB_Extent_Polygon == '#' or not MB_Extent_Polygon:
    MB_Extent_Polygon = "E:\\HYPACK_Projects\\2020_DNR_Lakes\\2020-07_MilanCityLake\\GIS\\MilanCityLake.gdb\\MilanCityLake_MBpoly" # provide a default value if unspecified

Final_xyz_map_thinned_points = arcpy.GetParameterAsText(4)
if Final_xyz_map_thinned_points == '#' or not Final_xyz_map_thinned_points:
    Final_xyz_map_thinned_points = "E:\\HYPACK_Projects\\2020_DNR_Lakes\\2020-07_MilanCityLake\\Provisional-Final\\MilanCityLake2020_bathy_pts.shp" # provide a default value if unspecified

Map_Resolution__meters_ = arcpy.GetParameterAsText(5)
if Map_Resolution__meters_ == '#' or not Map_Resolution__meters_:
    Map_Resolution__meters_ = "0.5" # provide a default value if unspecified

# Local variables:
String2 = "%Output QA Geodatabase%\\%Lake Name%_MBextentRaster"
v_String2_ = "%String2%"
v_Lake_Name__CUBEUncertInterp = "%Output QA Geodatabase%\\%Lake Name%_CUBEUncertInterp"
v_Lake_Name__CUBEUncertraster_tif = "%QA Folder%\\%Lake Name%_CUBEUncertraster.tif"
String1 = "%Output QA Geodatabase%\\%Lake Name%_CUBEUncertInterp"

# Process: Polygon to Raster
arcpy.PolygonToRaster_conversion(MB_Extent_Polygon, "Coffee", v_String2_, "CELL_CENTER", "NONE", "0.5")

# Process: Natural Neighbor
arcpy.NaturalNeighbor_3d(Final_xyz_map_thinned_points, "CUBE_Uncer", v_Lake_Name__CUBEUncertInterp, Map_Resolution__meters_)

# Process: Con
arcpy.gp.Con_sa(v_String2_, v_Lake_Name__CUBEUncertInterp, v_Lake_Name__CUBEUncertraster_tif, "", "\"VALUE\"=0")

