# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ThalwegLinearInterpolation_ModelBuilderArcpyTemplate.py
# Created on: 2021-08-09 10:54:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: ThalwegLinearInterpolation_ModelBuilderArcpyTemplate <XYZ_Points> <LR_Shapefile> <LAS_Points> <Distance> <Output_GDB> <Interpolation_Iteration> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
XYZ_Points = arcpy.GetParameterAsText(0)

LR_Shapefile = arcpy.GetParameterAsText(1)

LAS_Points = arcpy.GetParameterAsText(2)

Distance = arcpy.GetParameterAsText(3)

Output_GDB = arcpy.GetParameterAsText(4)

Interpolation_Iteration = arcpy.GetParameterAsText(5)

# Local variables:
spjoin1 = "%Output GDB%\\spjoin1"
spjoin2 = "%Output GDB%\\spjoin2"
linear_coords_Interpolation_Iteration_ = "%Output GDB%\\linear_coords%Interpolation Iteration%"
generatedpoints__2_ = linear_coords_Interpolation_Iteration_
generatedpoints__3_ = generatedpoints__2_
generatedpoints__4_ = generatedpoints__3_
generatedpoints__5_ = generatedpoints__4_
generatedpoints__6_ = generatedpoints__5_
generatedpoints__7_ = generatedpoints__6_
generatedpoints__9_ = generatedpoints__7_
generatedpoints__8_ = generatedpoints__9_
generatedpoints__10_ = generatedpoints__8_

# Process: Spatial Join
arcpy.SpatialJoin_analysis(LR_Shapefile, XYZ_Points, spjoin1, "JOIN_ONE_TO_ONE", "KEEP_ALL", "", "INTERSECT", "", "")

# Process: Spatial Join (2)
arcpy.SpatialJoin_analysis(spjoin1, LAS_Points, spjoin2, "JOIN_ONE_TO_ONE", "KEEP_ALL", "", "INTERSECT", "", "")

# Process: Generate Points Along Lines
arcpy.GeneratePointsAlongLines_management(spjoin2, linear_coords_Interpolation_Iteration_, "DISTANCE", Distance, "", "")

# Process: Add XY Coordinates
arcpy.AddXY_management(linear_coords_Interpolation_Iteration_)

# Process: Add Field
arcpy.AddField_management(generatedpoints__2_, "LineLength", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(generatedpoints__3_, "Euc_Dist", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(generatedpoints__4_, "Gradient", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(generatedpoints__5_, "Z_interp", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(generatedpoints__6_, "LineLength", "[SHAPE_Length]*3.2808", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(generatedpoints__7_, "Euc_Dist", "(Sqr(([POINT_X] - [X]) ^ 2 + ([POINT_Y] - [Y]) ^ 2))*3.2808", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(generatedpoints__9_, "Gradient", "( [Z_1] - [Z]) / [LineLength]", "VB", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(generatedpoints__8_, "Z_interp", "[Z] +( [Gradient] * [Euc_Dist] )", "VB", "")

