# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TINQA_ModelBuilderArcPyTemplate.py
# Created on: 2021-09-30 13:50:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: TINQA_ModelBuilderArcPyTemplate <Lake_Name> <Final_Bathy_Points_Shapefile> <Output_QA_Geodatabase> <Final_Edited_TIN> <QA_Folder> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Lake_Name = arcpy.GetParameterAsText(0)

Final_Bathy_Points_Shapefile = arcpy.GetParameterAsText(1)

Output_QA_Geodatabase = arcpy.GetParameterAsText(2)

Final_Edited_TIN = arcpy.GetParameterAsText(3)

QA_Folder = arcpy.GetParameterAsText(4)

# Local variables:
v_Lake_Name__TINQAselect = "%Output QA Geodatabase%\\%Lake Name%_TINQAselect"
v_Lake_Name__QAselect__3_ = v_Lake_Name__TINQAselect
v_Lake_Name__QAselect__2_ = v_Lake_Name__QAselect__3_
Output_Feature_Class = v_Lake_Name__QAselect__2_
v_Lake_Name__TINQAtable = Output_Feature_Class
v_Lake_Name__TINQA_xls = "%QA Folder%\\%Lake Name%_TINQA.xls"

# Process: Select
arcpy.Select_analysis(Final_Bathy_Points_Shapefile, v_Lake_Name__TINQAselect, "\"QA\" =1")

# Process: Add Field
arcpy.AddField_management(v_Lake_Name__TINQAselect, "Z_MBelev", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(v_Lake_Name__QAselect__3_, "Z_MBelev", "[Z]", "VB", "")

# Process: Add Surface Information
arcpy.AddSurfaceInformation_3d(v_Lake_Name__QAselect__2_, Final_Edited_TIN, "Z", "LINEAR", "", "1", "0", "NO_FILTER")

# Process: Table to Table
arcpy.TableToTable_conversion(Output_Feature_Class, Output_QA_Geodatabase, "%Lake Name%_TINQAtable", "", "X \"X\" true true false 8 Double 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,X,-1,-1;Y \"Y\" true true false 8 Double 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,Y,-1,-1;Z \"Z\" true true false 8 Double 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,Z,-1,-1;CUBE_Uncer \"CUBE_Uncer\" true true false 8 Double 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,CUBE_Uncer,-1,-1;Map \"Map\" true true false 4 Long 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,Map,-1,-1;QA \"QA\" true true false 4 Long 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,QA,-1,-1;Source \"Source\" true true false 254 Text 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,Source,-1,-1;Z_MBelev \"Z_MBelev\" true true false 0 Double 0 0 ,First,#,%Output QA Geodatabase%\\%Lake Name%_TINQAselect,Z_MBelev,-1,-1", "")

# Process: Table To Excel
arcpy.TableToExcel_conversion(v_Lake_Name__TINQAtable, v_Lake_Name__TINQA_xls, "ALIAS", "CODE")

