# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TINQA_ModelBuilderArcPyTemplate.py
# Created on: 2021-09-29 14:28:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: TINQA_ModelBuilderArcPyTemplate <Lake_Name> <Final_Bathy_Points_Shapefile> <Output_QA_Geodatabase> <Final_Edited_TIN>
# Description:
# ---------------------------------------------------------------------------


# Script arguments
Output_QA_Geodatabase = arcpy.GetParameterAsText(0)
QA_Folder = arcpy.GetParameterAsText(1)
Lake_Name = arcpy.GetParameterAsText(2)
Final_Edited_TIN = arcpy.GetParameterAsText(3)
Final_Bathy_Points_Shapefile = arcpy.GetParameterAsText(4)



arcpy.env.overwriteOutput = True
arcpy.env.workspace = Output_QA_Geodatabase

# Local variables:
tinQAselect = Output_QA_Geodatabase + "\\" + Lake_Name + "_TINQAselect"
tin_exceldoc = QA_Folder + "\\" + Lake_Name + "_TINQA.xls"


# Process: Select points in the Final Bathy Points dataset where QA=1
arcpy.AddMessage("Selecting the QA=1 points...")
arcpy.Select_analysis(Final_Bathy_Points_Shapefile, tinQAselect, "\"QA\" =1")

# Process: Add Field to the selected points dataset called Z_MBelev
arcpy.AddMessage("Getting elevation information from the TIN...")
arcpy.AddField_management(tinQAselect, "Z_MBelev", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field of Z_MBelev to be the current Z column
arcpy.CalculateField_management(tinQAselect, "Z_MBelev", "[Z]", "VB", "")

# Process: Add Surface Information from the TIN --> overwriting the TIN elevation in the Z column
arcpy.AddSurfaceInformation_3d(tinQAselect, Final_Edited_TIN, "Z", "LINEAR", "", "1", "0", "NO_FILTER")


# Process: Table To Excel
arcpy.AddMessage("Exporting results to an Excel document...")
arcpy.TableToExcel_conversion(tinQAselect, tin_exceldoc, "ALIAS", "CODE")

